### ISSUE TITLE
V3 Todo

### ISSUE THREAD

**Issue by andradesavio9073** [andradesavio9073/haruhi#36]
- [x] Fix Manga Selector
- [x] Style Manga Selector Area
- [x] Reduce Manga Updater Threshold to 0.6 because of 4-Koma
- [x] Invert Manga Next/Previous Buttons so that MdPrevious is actually the next chapter
- [x] Anime/Manga Sidebar dates to be ~~internationalized~~ formatted with month day, year
- [x] Fix MediaListEditor Support for Manga (fix status display to be currently reading, plan to read, etc.) 
- [ ] #40
- [x] Add Tooltip to video player hover
- [x] Switch to useQuery wherever possible
- [x] Character Page
- [x] Staff Page
- [x] Basic Search
- [x] Advanced Search
- [x] Link Logout to api
- [x] Make User Lists Pages
- [x] Seasonal Anime Page
- [x] User Preferences Pages
- [ ] #39
- [x] Make a Logo
- [x] Update Favicon
- [x] Add Meta For all Pages
- [x] Add Studio page
- [x] Debounce Filters on Advanced Search
- [x] Fix Hyperlinks on Staff Pages
- [ ] #38

**Comment by andradesavio9073** [comment]
V3 is mostly done and ready to be launched. The remaining Todos will be done in due time
